spring.application.name=social-media-food

#spring.datasource.url=jdbc:postgresql://social-food_DB/social-food
spring.datasource.url=jdbc:postgresql://localhost/social-food
spring.datasource.username=postgres
#spring.datasource.password=postgres
spring.datasource.password=1111
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

logging.file.name=logs/application.log
logging.level.root=INFO
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.file.max-size=10MB
logging.file.max-history=10

upload.path=src/main/resources/static/uploads
