package com.foodsocial.social_media_food;

import com.foodsocial.social_media_food.accessingdatasql.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;
import java.util.regex.Pattern;

import com.foodsocial.social_media_food.repos.UserRepository;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    private static final String EMAIL_REGEX = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,6}$";
    private static final Pattern EMAIL_PATTERN = Pattern.compile(EMAIL_REGEX);

    private static final String USERNAME_REGEX = "^(?!-)[A-Za-z0-9-]+(?<!-)$";
    private static final Pattern USERNAME_PATTERN = Pattern.compile(USERNAME_REGEX);

    private final BCryptPasswordEncoder passwordEncoder = new BCryptPasswordEncoder();

    @PostMapping(path="/register")
    public @ResponseBody String registerUser(@RequestParam String name,
                                             @RequestParam String email,
                                             @RequestParam String password) {
        if (!EMAIL_PATTERN.matcher(email).matches()) {
            return "Invalid email format";
        }

        if (!USERNAME_PATTERN.matcher(name).matches()) {
            return "Invalid username format. Username may only contain alphanumeric characters or single " +
                    "hyphens, and cannot begin or end with a hyphen.";
        }

        User n = new User();
        n.setUsername(name);
        n.setEmail(email);
        //TODO сделать проверку на ввод сложного пароля
        n.setPassword(passwordEncoder.encode(password));
        userRepository.save(n);
        return "User registered successfully";
    }

    @PostMapping(path = "/login")
    public @ResponseBody ResponseEntity<String> loginUser(@RequestParam String identifier,
                                                          @RequestParam String password) {
        // Проверка на email-формат для определения, искать ли пользователя по email или логину
        boolean isEmail = EMAIL_PATTERN.matcher(identifier).matches();
        Optional<User> userOpt = isEmail
                ? userRepository.findByEmail(identifier)
                : userRepository.findByUsername(identifier);

        if (userOpt.isPresent()) {
            User user = userOpt.get();

            // Сравниваем захешированный пароль
            if (passwordEncoder.matches(password, user.getPassword())) {
                return ResponseEntity.ok("Login successful");
            } else {
                return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("Incorrect password");
            }
        } else {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body("User not found");
        }
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}