package com.foodsocial.social_media_food;

import com.foodsocial.social_media_food.accessingdatasql.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import java.util.regex.Pattern;

import com.foodsocial.social_media_food.repos.UserRepository;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    private static final String EMAIL_REGEX = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,6}$";
    private static final Pattern EMAIL_PATTERN = Pattern.compile(EMAIL_REGEX);

    private final BCryptPasswordEncoder passwordEncoder = new BCryptPasswordEncoder();

    @PostMapping(path="/register")
    public @ResponseBody String registerUser(@RequestParam String name,
                                             @RequestParam String email,
                                             @RequestParam String password) {
        if (!EMAIL_PATTERN.matcher(email).matches()) {
            return "Invalid email format";
        }

        User n = new User();
        n.setUsername(name);
        n.setEmail(email);
        n.setPassword(passwordEncoder.encode(password));
        userRepository.save(n);
        return "User registered successfully";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}