spring.application.name=social-media-food
spring.datasource.url=jdbc:postgresql://localhost/social-food
spring.datasource.username=postgres
spring.datasource.password=1111
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update