spring.application.name=social-media-food
spring.thymeleaf.check-template-location=false
#spring.jpa.open-in-view=false

spring.profiles.active=main
spring.profiles.group.main=main
spring.profiles.group.docker=docker

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

logging.file.name=logs/application.log
logging.level.root=INFO
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.file.max-size=10MB
logging.file.max-history=10

upload.path=src/main/resources/static/uploads
